#!/bin/bash
set -e

echo "Starting RDP Setup (GNOME System Remote Desktop)..."

# 1. Set Linux Password for 'opc' (Required for GDM Login)
echo "Setting password for user 'opc'..."
echo "opc:antigravity" | sudo chpasswd

# 2. Ensure Graphical Target
echo "Setting graphical target..."
sudo systemctl set-default graphical.target
sudo systemctl isolate graphical.target || echo "Graphical target unavailable or already active."

# 3. Configure System RDP via grdctl
echo "Configuring System RDP..."
sudo grdctl --system rdp enable
sudo grdctl --system rdp set-credentials "antigravity" "antigravity"
# Note: TLS cert is usually auto-generated by --system. If not, we ignore for now (RDP allows untrusted).

echo "System RDP Configured."
echo "RDP User: antigravity"
echo "RDP Pass: antigravity"
echo "Linux User: opc"
echo "Linux Pass: antigravity"

# 4. Start Cloudflare Tunnel
echo "Starting Cloudflare Tunnel for RDP..."
BASE_DIR="$HOME/remote-desktop"
BIN_DIR="$BASE_DIR/bin"
LOG_DIR="$BASE_DIR/logs"
mkdir -p "$LOG_DIR" "$BIN_DIR"

# Download cloudflared if missing
if [ ! -f "$BIN_DIR/cloudflared" ]; then
    echo "Downloading Cloudflared..."
    curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o "$BIN_DIR/cloudflared"
    chmod +x "$BIN_DIR/cloudflared"
fi

pkill -f "cloudflared tunnel" || true

"$BIN_DIR/cloudflared" tunnel --url tcp://localhost:3389 > "$LOG_DIR/tunnel_rdp.log" 2>&1 &

echo "⏳ Waiting for tunnel URL..."
sleep 8
URL=$(grep -o 'tcp://.*\.trycloudflare\.com:[0-9]*' "$LOG_DIR/tunnel_rdp.log" | head -n 1)

if [ -z "$URL" ]; then
    echo "⚠️ Tunnel URL not found yet. Check logs/tunnel_rdp.log"
else
    echo "=========================================="
    echo "RDP ACCESS URL: $URL"
    echo "RDP Creds: antigravity / antigravity"
    echo "Login: opc / antigravity"
    echo "=========================================="
fi
